#pragma once

#define NH_CPU_HZ 1789773

#define NH_ADDRESSABLE_SIZE (64 * 1024) // 16bit addressable memory

#define NH_INTERNAL_RAM_SIZE (2 * 1024) // 2KiB
#define NH_INTERNAL_RAM_ADDR_HEAD 0x0000
#define NH_INTERNAL_RAM_ADDR_TAIL 0x07FF

#define NH_RAM_ADDR_HEAD 0x0000
#define NH_RAM_ADDR_TAIL 0x1FFF // including mirror
#define NH_RAM_ADDR_MASK 0x07FF // leftmost 5 bits zero

#define NH_PPU_ADDRESSABLE_SIZE (16 * 1024) // 14bit addressable memory
#define NH_PPU_ADDR_MASK 0x3FFF
#define NH_PPU_INTERNAL_RAM_SIZE (2 * 1024) // 2KiB

#define NH_OAM_SP_SIZE 4
#define NH_MAX_SP_NUM 64
#define NH_OAM_SIZE (NH_MAX_SP_NUM * NH_OAM_SP_SIZE)
#define NH_MAX_VISIBLE_SP_NUM 8
#define NH_SEC_OAM_SIZE (NH_MAX_VISIBLE_SP_NUM * NH_OAM_SP_SIZE)

#define NH_PPU_REG_ADDR_HEAD 0x2000
#define NH_PPU_REG_ADDR_TAIL 0x3FFF // including mirror
#define NH_PPU_REG_ADDR_MASK 0x0007 // rightmost 3 bits 1
#define NH_PPUSTATUS_ADDR 0x2002
#define NH_OAMDMA_ADDR 0x4014

#define NH_PATTERN_TILE_WIDTH 8
#define NH_PATTERN_TILE_HEIGHT 8
#define NH_PATTERN_0_ADDR_HEAD 0x0000
#define NH_PATTERN_1_ADDR_HEAD 0x1000
#define NH_PATTERN_ADDR_HEAD NH_PATTERN_0_ADDR_HEAD
#define NH_PATTERN_ADDR_TAIL 0x1FFF

#define NH_NT_ONE_SIZE 0x0400 // bytes
#define NH_NT_0_ADDR_HEAD 0x2000
#define NH_NT_2_ADDR_HEAD 0x2800
#define NH_NT_ADDR_HEAD NH_NT_0_ADDR_HEAD
#define NH_NT_ADDR_TAIL 0x2FFF
#define NH_NT_H_MIRROR_ADDR_MASK 0xFBFF
#define NH_NT_V_MIRROR_ADDR_MASK 0xF7FF
#define NH_NT_1_MIRROR_ADDR_MASK 0xF3FF

#define NH_NT_MIRROR_ADDR_HEAD 0x3000
#define NH_NT_MIRROR_ADDR_TAIL 0x3EFF
#define NH_NT_MIRROR_ADDR_MASK 0xEFFF

#define NH_PALETTE_SIZE 32
#define NH_PALETTE_ADDR_BG_BACKDROP 0x3F00
#define NH_PALETTE_ADDR_BACKDROP_MASK 0xFFE3 // & to backdrop
#define NH_PALETTE_ADDR_HEAD 0x3F00
#define NH_PALETTE_ADDR_TAIL 0x3FFF
#define NH_PALETTE_ADDR_MASK 0x001F        // rightmost 5 bits
#define NH_PALETTE_ADDR_MIRROR_MASK 0x0003 // rightmost 2 bits (modulo 4)
#define NH_PALETTE_ADDR_BG_MASK 0xFF0F     // & to background palette
// used to get background palette color
#define NH_PALETTE_ADDR_BG_OR_MASK 0x3F00
// used to get sprite palette color
#define NH_PALETTE_ADDR_SP_OR_MASK 0x3F10

#define NH_PPU_INVALID_ADDR_HEAD 0x4000
#define NH_PPU_INVALID_ADDR_TAIL 0xFFFF
#define NH_PPU_INVALID_ADDR_MASK 0x3FFF

#define NH_SCANLINE_CYCLES 341

#define NH_APU_PULSE1_DUTY_ADDR 0x4000
#define NH_APU_DMC_SAMPLE_LENGTH_ADDR 0x4013
#define NH_APU_STATUS_ADDR 0x4015
#define NH_APU_FC_ADDR 0x4017
#define NH_APU_REG_ADDR_HEAD NH_APU_PULSE1_DUTY_ADDR
#define NH_APU_REG_ADDR_TAIL NH_APU_FC_ADDR

#define NH_CTRL1_REG_ADDR 0x4016
#define NH_CTRL2_REG_ADDR 0x4017
