#include "console/cpu/cpu.hpp"
#include "console/cpu/opcode_exec.hpp"

#define EXEC_OF(i_opcode_name) CPU::OpcodeExec::exec_##i_opcode_name

namespace ln {

// Maybe we should write a script to generate this...

CPU::InstructionProperty CPU::s_instr_map[256] = {
    // http://www.oxyron.de/html/opcodes02.html
    /* clang-format off */
    // -- 0x
    {Opcode::BRK, AddressMode::IMP, EXEC_OF(brk), 7, 0},
    {Opcode::ORA, AddressMode::IZX, EXEC_OF(ora), 6, 0},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::SLO, AddressMode::IZX, EXEC_OF(slo), 8, 0},
    {Opcode::NOP, AddressMode::ZP0, EXEC_OF(nop), 3, 0},
    {Opcode::ORA, AddressMode::ZP0, EXEC_OF(ora), 3, 0},
    {Opcode::ASL, AddressMode::ZP0, EXEC_OF(asl), 5, 0},
    {Opcode::SLO, AddressMode::ZP0, EXEC_OF(slo), 5, 0},
    {Opcode::PHP, AddressMode::IMP, EXEC_OF(php), 3, 0},
    {Opcode::ORA, AddressMode::IMM, EXEC_OF(ora), 2, 0},
    {Opcode::ASL, AddressMode::ACC, EXEC_OF(asl), 2, 0},
    {Opcode::ANC, AddressMode::IMM, EXEC_OF(anc), 2, 0},
    {Opcode::NOP, AddressMode::ABS, EXEC_OF(nop), 4, 0},
    {Opcode::ORA, AddressMode::ABS, EXEC_OF(ora), 4, 0},
    {Opcode::ASL, AddressMode::ABS, EXEC_OF(asl), 6, 0},
    {Opcode::SLO, AddressMode::ABS, EXEC_OF(slo), 6, 0},
    // -- 1x
    {Opcode::BPL, AddressMode::REL, EXEC_OF(brk), 2, 0},
    {Opcode::ORA, AddressMode::IZY, EXEC_OF(ora), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::SLO, AddressMode::IZY, EXEC_OF(slo), 8, 0},
    {Opcode::NOP, AddressMode::ZPX, EXEC_OF(nop), 4, 0},
    {Opcode::ORA, AddressMode::ZPX, EXEC_OF(ora), 4, 0},
    {Opcode::ASL, AddressMode::ZPX, EXEC_OF(asl), 6, 0},
    {Opcode::SLO, AddressMode::ZPX, EXEC_OF(slo), 6, 0},
    {Opcode::CLC, AddressMode::IMP, EXEC_OF(php), 2, 0},
    {Opcode::ORA, AddressMode::ABY, EXEC_OF(ora), 4, 1},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(asl), 2, 0},
    {Opcode::SLO, AddressMode::ABY, EXEC_OF(anc), 7, 0},
    {Opcode::NOP, AddressMode::ABX, EXEC_OF(nop), 4, 1},
    {Opcode::ORA, AddressMode::ABX, EXEC_OF(ora), 4, 1},
    {Opcode::ASL, AddressMode::ABX, EXEC_OF(asl), 7, 0},
    {Opcode::SLO, AddressMode::ABX, EXEC_OF(slo), 7, 0},
    // -- 2x
    {Opcode::JSR, AddressMode::ABS, EXEC_OF(jsr), 6, 0},
    {Opcode::AND, AddressMode::IZX, EXEC_OF(and), 6, 0},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::RLA, AddressMode::IZX, EXEC_OF(rla), 8, 0},
    {Opcode::BIT, AddressMode::ZP0, EXEC_OF(bit), 3, 0},
    {Opcode::AND, AddressMode::ZP0, EXEC_OF(and), 3, 0},
    {Opcode::ROL, AddressMode::ZP0, EXEC_OF(rol), 5, 0},
    {Opcode::RLA, AddressMode::ZP0, EXEC_OF(rla), 5, 0},
    {Opcode::PLP, AddressMode::IMP, EXEC_OF(plp), 4, 0},
    {Opcode::AND, AddressMode::IMM, EXEC_OF(and), 2, 0},
    {Opcode::ROL, AddressMode::IMP, EXEC_OF(rol), 2, 0},
    {Opcode::ANC, AddressMode::IMM, EXEC_OF(anc), 2, 0},
    {Opcode::BIT, AddressMode::ABS, EXEC_OF(bit), 4, 0},
    {Opcode::AND, AddressMode::ABS, EXEC_OF(and), 4, 0},
    {Opcode::ROL, AddressMode::ABS, EXEC_OF(rol), 6, 0},
    {Opcode::RLA, AddressMode::ABS, EXEC_OF(rla), 6, 0},
    // -- 3x
    {Opcode::BMI, AddressMode::REL, EXEC_OF(bmi), 2, 0},
    {Opcode::AND, AddressMode::IZY, EXEC_OF(and), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::RLA, AddressMode::IZY, EXEC_OF(rla), 8, 0},
    {Opcode::NOP, AddressMode::ZPX, EXEC_OF(nop), 4, 0},
    {Opcode::AND, AddressMode::ZPX, EXEC_OF(and), 4, 0},
    {Opcode::ROL, AddressMode::ZPX, EXEC_OF(rol), 6, 0},
    {Opcode::RLA, AddressMode::ZPX, EXEC_OF(rla), 6, 0},
    {Opcode::SEC, AddressMode::IMP, EXEC_OF(sec), 2, 0},
    {Opcode::AND, AddressMode::ABY, EXEC_OF(and), 4, 1},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(nop), 2, 0},
    {Opcode::RLA, AddressMode::ABY, EXEC_OF(rla), 7, 0},
    {Opcode::NOP, AddressMode::ABX, EXEC_OF(nop), 4, 1},
    {Opcode::AND, AddressMode::ABX, EXEC_OF(and), 4, 1},
    {Opcode::ROL, AddressMode::ABX, EXEC_OF(rol), 7, 0},
    {Opcode::RLA, AddressMode::ABX, EXEC_OF(rla), 7, 0},
    // -- 4x
    {Opcode::RTI, AddressMode::IMP, EXEC_OF(rti), 6, 0},
    {Opcode::EOR, AddressMode::IZX, EXEC_OF(eor), 6, 0},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::SRE, AddressMode::IZX, EXEC_OF(sre), 8, 0},
    {Opcode::NOP, AddressMode::ZP0, EXEC_OF(nop), 3, 0},
    {Opcode::EOR, AddressMode::ZP0, EXEC_OF(eor), 3, 0},
    {Opcode::LSR, AddressMode::ZP0, EXEC_OF(lsr), 5, 0},
    {Opcode::SRE, AddressMode::ZP0, EXEC_OF(sre), 5, 0},
    {Opcode::PHA, AddressMode::IMP, EXEC_OF(pha), 3, 0},
    {Opcode::EOR, AddressMode::IMM, EXEC_OF(eor), 2, 0},
    {Opcode::LSR, AddressMode::IMP, EXEC_OF(lsr), 2, 0},
    {Opcode::ALR, AddressMode::IMM, EXEC_OF(alr), 2, 0},
    {Opcode::JMP, AddressMode::ABS, EXEC_OF(jmp), 3, 0},
    {Opcode::EOR, AddressMode::ABS, EXEC_OF(eor), 4, 0},
    {Opcode::LSR, AddressMode::ABS, EXEC_OF(lsr), 6, 0},
    {Opcode::SRE, AddressMode::ABS, EXEC_OF(sre), 6, 0},
    // -- 5x
    {Opcode::BVC, AddressMode::REL, EXEC_OF(bvc), 2, 0},
    {Opcode::EOR, AddressMode::IZY, EXEC_OF(eor), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::SRE, AddressMode::IZY, EXEC_OF(sre), 8, 0},
    {Opcode::NOP, AddressMode::ZPX, EXEC_OF(nop), 4, 0},
    {Opcode::EOR, AddressMode::ZPX, EXEC_OF(eor), 4, 0},
    {Opcode::LSR, AddressMode::ZPX, EXEC_OF(lsr), 6, 0},
    {Opcode::SRE, AddressMode::ZPX, EXEC_OF(sre), 6, 0},
    {Opcode::CLI, AddressMode::IMP, EXEC_OF(cli), 2, 0},
    {Opcode::EOR, AddressMode::ABY, EXEC_OF(eor), 4, 1},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(nop), 2, 0},
    {Opcode::SRE, AddressMode::ABY, EXEC_OF(sre), 7, 0},
    {Opcode::NOP, AddressMode::ABX, EXEC_OF(nop), 4, 1},
    {Opcode::EOR, AddressMode::ABX, EXEC_OF(eor), 4, 1},
    {Opcode::LSR, AddressMode::ABX, EXEC_OF(lsr), 7, 0},
    {Opcode::SRE, AddressMode::ABX, EXEC_OF(sre), 7, 0},
    // -- 6x
    {Opcode::RTS, AddressMode::IMP, EXEC_OF(rts), 6, 0},
    {Opcode::ADC, AddressMode::IZX, EXEC_OF(adc), 6, 0},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::RRA, AddressMode::IZX, EXEC_OF(rra), 8, 0},
    {Opcode::NOP, AddressMode::ZP0, EXEC_OF(nop), 3, 0},
    {Opcode::ADC, AddressMode::ZP0, EXEC_OF(adc), 3, 0},
    {Opcode::ROR, AddressMode::ZP0, EXEC_OF(ror), 5, 0},
    {Opcode::RRA, AddressMode::ZP0, EXEC_OF(rra), 5, 0},
    {Opcode::PLA, AddressMode::IMP, EXEC_OF(pla), 4, 0},
    {Opcode::ADC, AddressMode::IMM, EXEC_OF(adc), 2, 0},
    {Opcode::ROR, AddressMode::IMP, EXEC_OF(ror), 2, 0},
    {Opcode::ARR, AddressMode::IMM, EXEC_OF(arr), 2, 0},
    {Opcode::JMP, AddressMode::IND, EXEC_OF(jmp), 5, 0},
    {Opcode::ADC, AddressMode::ABS, EXEC_OF(adc), 4, 0},
    {Opcode::ROR, AddressMode::ABS, EXEC_OF(ror), 6, 0},
    {Opcode::RRA, AddressMode::ABS, EXEC_OF(rra), 6, 0},
    // -- 7x
    {Opcode::BVS, AddressMode::REL, EXEC_OF(bvs), 2, 0},
    {Opcode::ADC, AddressMode::IZY, EXEC_OF(adc), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::RRA, AddressMode::IZY, EXEC_OF(rra), 8, 0},
    {Opcode::NOP, AddressMode::ZPX, EXEC_OF(nop), 4, 0},
    {Opcode::ADC, AddressMode::ZPX, EXEC_OF(adc), 4, 0},
    {Opcode::ROR, AddressMode::ZPX, EXEC_OF(ror), 6, 0},
    {Opcode::RRA, AddressMode::ZPX, EXEC_OF(rra), 6, 0},
    {Opcode::SEI, AddressMode::IMP, EXEC_OF(sei), 2, 0},
    {Opcode::ADC, AddressMode::ABY, EXEC_OF(adc), 4, 1},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(nop), 2, 0},
    {Opcode::RRA, AddressMode::ABY, EXEC_OF(rra), 7, 0},
    {Opcode::NOP, AddressMode::ABX, EXEC_OF(nop), 4, 1},
    {Opcode::ADC, AddressMode::ABX, EXEC_OF(adc), 4, 1},
    {Opcode::ROR, AddressMode::ABX, EXEC_OF(ror), 7, 0},
    {Opcode::RRA, AddressMode::ABX, EXEC_OF(rra), 7, 0},
    // -- 8x
    {Opcode::NOP, AddressMode::IMM, EXEC_OF(nop), 2, 0},
    {Opcode::STA, AddressMode::IZX, EXEC_OF(sta), 6, 0},
    {Opcode::NOP, AddressMode::IMM, EXEC_OF(nop), 2, 0},
    {Opcode::SAX, AddressMode::IZX, EXEC_OF(sax), 6, 0},
    {Opcode::STY, AddressMode::ZP0, EXEC_OF(sty), 3, 0},
    {Opcode::STA, AddressMode::ZP0, EXEC_OF(sta), 3, 0},
    {Opcode::STX, AddressMode::ZP0, EXEC_OF(stx), 3, 0},
    {Opcode::SAX, AddressMode::ZP0, EXEC_OF(sax), 3, 0},
    {Opcode::DEY, AddressMode::IMP, EXEC_OF(dey), 2, 0},
    {Opcode::NOP, AddressMode::IMM, EXEC_OF(nop), 2, 0},
    {Opcode::TXA, AddressMode::IMP, EXEC_OF(txa), 2, 0},
    {Opcode::XAA, AddressMode::IMM, EXEC_OF(xaa), 2, 0},
    {Opcode::STY, AddressMode::ABS, EXEC_OF(sty), 4, 0},
    {Opcode::STA, AddressMode::ABS, EXEC_OF(sta), 4, 0},
    {Opcode::STX, AddressMode::ABS, EXEC_OF(stx), 4, 0},
    {Opcode::SAX, AddressMode::ABS, EXEC_OF(sax), 4, 0},
    // -- 9x
    {Opcode::BCC, AddressMode::REL, EXEC_OF(bcc), 2, 0},
    {Opcode::STA, AddressMode::IZY, EXEC_OF(sta), 6, 0},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::AHX, AddressMode::IZY, EXEC_OF(ahx), 6, 0},
    {Opcode::STY, AddressMode::ZPX, EXEC_OF(sty), 4, 0},
    {Opcode::STA, AddressMode::ZPX, EXEC_OF(sta), 4, 0},
    {Opcode::STX, AddressMode::ZPY, EXEC_OF(stx), 4, 0},
    {Opcode::SAX, AddressMode::ZPY, EXEC_OF(sax), 4, 0},
    {Opcode::TYA, AddressMode::IMP, EXEC_OF(tya), 2, 0},
    {Opcode::STA, AddressMode::ABY, EXEC_OF(sta), 5, 0},
    {Opcode::TXS, AddressMode::IMP, EXEC_OF(txs), 2, 0},
    {Opcode::TAS, AddressMode::ABY, EXEC_OF(tas), 5, 0},
    {Opcode::SHY, AddressMode::ABX, EXEC_OF(shy), 5, 0},
    {Opcode::STA, AddressMode::ABX, EXEC_OF(sta), 5, 0},
    {Opcode::SHX, AddressMode::ABY, EXEC_OF(shx), 5, 0},
    {Opcode::AHX, AddressMode::ABY, EXEC_OF(ahx), 5, 0},
    // -- Ax
    {Opcode::LDY, AddressMode::IMM, EXEC_OF(ldy), 2, 0},
    {Opcode::LDA, AddressMode::IZX, EXEC_OF(lda), 6, 0},
    {Opcode::LDX, AddressMode::IMM, EXEC_OF(ldx), 2, 0},
    {Opcode::LAX, AddressMode::IZX, EXEC_OF(lax), 6, 0},
    {Opcode::LDY, AddressMode::ZP0, EXEC_OF(ldy), 3, 0},
    {Opcode::LDA, AddressMode::ZP0, EXEC_OF(lda), 3, 0},
    {Opcode::LDX, AddressMode::ZP0, EXEC_OF(ldx), 3, 0},
    {Opcode::LAX, AddressMode::ZP0, EXEC_OF(lax), 3, 0},
    {Opcode::TAY, AddressMode::IMP, EXEC_OF(tay), 2, 0},
    {Opcode::LDA, AddressMode::IMM, EXEC_OF(lda), 2, 0},
    {Opcode::TAX, AddressMode::IMP, EXEC_OF(tax), 2, 0},
    {Opcode::LAX, AddressMode::IMM, EXEC_OF(lax), 2, 0},
    {Opcode::LDY, AddressMode::ABS, EXEC_OF(ldy), 4, 0},
    {Opcode::LDA, AddressMode::ABS, EXEC_OF(lda), 4, 0},
    {Opcode::LDX, AddressMode::ABS, EXEC_OF(ldx), 4, 0},
    {Opcode::LAX, AddressMode::ABS, EXEC_OF(lax), 4, 0},
    // -- Bx
    {Opcode::BCS, AddressMode::REL, EXEC_OF(bcs), 2, 0},
    {Opcode::LDA, AddressMode::IZY, EXEC_OF(lda), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::LAX, AddressMode::IZY, EXEC_OF(lax), 5, 1},
    {Opcode::LDY, AddressMode::ZPX, EXEC_OF(ldy), 4, 0},
    {Opcode::LDA, AddressMode::ZPX, EXEC_OF(lda), 4, 0},
    {Opcode::LDX, AddressMode::ZPY, EXEC_OF(ldx), 4, 0},
    {Opcode::LAX, AddressMode::ZPY, EXEC_OF(lax), 4, 0},
    {Opcode::CLV, AddressMode::IMP, EXEC_OF(clv), 2, 0},
    {Opcode::LDA, AddressMode::ABY, EXEC_OF(lda), 4, 1},
    {Opcode::TSX, AddressMode::IMP, EXEC_OF(tsx), 2, 0},
    {Opcode::LAS, AddressMode::ABY, EXEC_OF(las), 4, 1},
    {Opcode::LDY, AddressMode::ABX, EXEC_OF(ldy), 4, 1},
    {Opcode::LDA, AddressMode::ABX, EXEC_OF(lda), 4, 1},
    {Opcode::LDX, AddressMode::ABY, EXEC_OF(ldx), 4, 1},
    {Opcode::LAX, AddressMode::ABY, EXEC_OF(lax), 4, 1},
    // -- Cx
    {Opcode::CPY, AddressMode::IMM, EXEC_OF(cpy), 2, 0},
    {Opcode::CMP, AddressMode::IZX, EXEC_OF(cmp), 6, 0},
    {Opcode::NOP, AddressMode::IMM, EXEC_OF(nop), 2, 0},
    {Opcode::DCP, AddressMode::IZX, EXEC_OF(dcp), 8, 0},
    {Opcode::CPY, AddressMode::ZP0, EXEC_OF(cpy), 3, 0},
    {Opcode::CMP, AddressMode::ZP0, EXEC_OF(cmp), 3, 0},
    {Opcode::DEC, AddressMode::ZP0, EXEC_OF(dec), 5, 0},
    {Opcode::DCP, AddressMode::ZP0, EXEC_OF(dcp), 5, 0},
    {Opcode::INY, AddressMode::IMP, EXEC_OF(iny), 2, 0},
    {Opcode::CMP, AddressMode::IMM, EXEC_OF(cmp), 2, 0},
    {Opcode::DEX, AddressMode::IMP, EXEC_OF(dex), 2, 0},
    {Opcode::AXS, AddressMode::IMM, EXEC_OF(axs), 2, 0},
    {Opcode::CPY, AddressMode::ABS, EXEC_OF(cpy), 4, 0},
    {Opcode::CMP, AddressMode::ABS, EXEC_OF(cmp), 4, 0},
    {Opcode::DEC, AddressMode::ABS, EXEC_OF(dec), 6, 0},
    {Opcode::DCP, AddressMode::ABS, EXEC_OF(dcp), 6, 0},
    // -- Dx
    {Opcode::BNE, AddressMode::REL, EXEC_OF(bne), 2, 0},
    {Opcode::CMP, AddressMode::IZY, EXEC_OF(cmp), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::DCP, AddressMode::IZY, EXEC_OF(dcp), 8, 0},
    {Opcode::NOP, AddressMode::ZPX, EXEC_OF(nop), 4, 0},
    {Opcode::CMP, AddressMode::ZPX, EXEC_OF(cmp), 4, 0},
    {Opcode::DEC, AddressMode::ZPX, EXEC_OF(dec), 6, 0},
    {Opcode::DCP, AddressMode::ZPX, EXEC_OF(dcp), 6, 0},
    {Opcode::CLD, AddressMode::IMP, EXEC_OF(cld), 2, 0},
    {Opcode::CMP, AddressMode::ABY, EXEC_OF(cmp), 4, 1},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(nop), 2, 0},
    {Opcode::DCP, AddressMode::ABY, EXEC_OF(dcp), 7, 0},
    {Opcode::NOP, AddressMode::ABX, EXEC_OF(nop), 4, 1},
    {Opcode::CMP, AddressMode::ABX, EXEC_OF(cmp), 4, 1},
    {Opcode::DEC, AddressMode::ABX, EXEC_OF(dec), 7, 0},
    {Opcode::DCP, AddressMode::ABX, EXEC_OF(dcp), 7, 0},
    // -- Ex
    {Opcode::CPX, AddressMode::IMM, EXEC_OF(cpx), 2, 0},
    {Opcode::SBC, AddressMode::IZX, EXEC_OF(sbc), 6, 0},
    {Opcode::NOP, AddressMode::IMM, EXEC_OF(nop), 2, 0},
    {Opcode::ISC, AddressMode::IZX, EXEC_OF(isc), 8, 0},
    {Opcode::CPX, AddressMode::ZP0, EXEC_OF(cpx), 3, 0},
    {Opcode::SBC, AddressMode::ZP0, EXEC_OF(sbc), 3, 0},
    {Opcode::INC, AddressMode::ZP0, EXEC_OF(inc), 5, 0},
    {Opcode::ISC, AddressMode::ZP0, EXEC_OF(isc), 5, 0},
    {Opcode::INX, AddressMode::IMP, EXEC_OF(inx), 2, 0},
    {Opcode::SBC, AddressMode::IMM, EXEC_OF(sbc), 2, 0},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(nop), 2, 0},
    {Opcode::SBC, AddressMode::IMM, EXEC_OF(sbc), 2, 0},
    {Opcode::CPX, AddressMode::ABS, EXEC_OF(cpx), 4, 0},
    {Opcode::SBC, AddressMode::ABS, EXEC_OF(sbc), 4, 0},
    {Opcode::INC, AddressMode::ABS, EXEC_OF(inc), 6, 0},
    {Opcode::ISC, AddressMode::ABS, EXEC_OF(isc), 6, 0},
    // -- Fx
    {Opcode::BEQ, AddressMode::REL, EXEC_OF(beq), 2, 0},
    {Opcode::SBC, AddressMode::IZY, EXEC_OF(sbc), 5, 1},
    {Opcode::KIL, AddressMode::IMP, EXEC_OF(kil), 0, 0},
    {Opcode::ISC, AddressMode::IZY, EXEC_OF(isc), 8, 0},
    {Opcode::NOP, AddressMode::ZPX, EXEC_OF(nop), 4, 0},
    {Opcode::SBC, AddressMode::ZPX, EXEC_OF(sbc), 4, 0},
    {Opcode::INC, AddressMode::ZPX, EXEC_OF(inc), 6, 0},
    {Opcode::ISC, AddressMode::ZPX, EXEC_OF(isc), 6, 0},
    {Opcode::SED, AddressMode::IMP, EXEC_OF(sed), 2, 0},
    {Opcode::SBC, AddressMode::ABY, EXEC_OF(sbc), 4, 1},
    {Opcode::NOP, AddressMode::IMP, EXEC_OF(nop), 2, 0},
    {Opcode::ISC, AddressMode::ABY, EXEC_OF(isc), 7, 0},
    {Opcode::NOP, AddressMode::ABX, EXEC_OF(nop), 4, 1},
    {Opcode::SBC, AddressMode::ABX, EXEC_OF(sbc), 4, 1},
    {Opcode::INC, AddressMode::ABX, EXEC_OF(inc), 7, 0},
    {Opcode::ISC, AddressMode::ABX, EXEC_OF(isc), 7, 0},
    /* clang-format on */
};

} // namespace ln
